delivery3.py:24: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  XX.iloc[:,1:] = scale(XX.iloc[:,1:], axis=0)
/home/andre/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:197: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  warnings.warn("Numerical issues were encountered "
0.0732552237543355
Measured target value for 2643: 24.0
Measured target value for 7272: 24.0
